const esc = value => String(value ?? "").replace(/[&<>\"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;", "'":"&#39;"}[ch]));

export function gerarHTMLDiagnostico({ projeto, autor, catalogo, itens, respostas, criadoEm, ref="DS-0001" }) {
  const total = itens.filter(i => respostas[i.id]?.status !== "na").length;
  const conformes = itens.filter(i => respostas[i.id]?.status === "c").length;
  const pct = total ? Math.round(conformes / total * 100) : 0;
  const achados = itens.filter(i => ["p","nc","an"].includes(respostas[i.id]?.status));
  const categorias = (catalogo?.categorias || []).map(cat => {
    const xs = itens.filter(i => i.categoriaId === cat.id); const den = xs.filter(i => respostas[i.id]?.status !== "na").length;
    const ok = xs.filter(i => respostas[i.id]?.status === "c").length;
    return `<tr><td>${esc(cat.id)} — ${esc(cat.nome)}</td><td>${den ? Math.round(ok/den*100) : 0}%</td></tr>`;
  }).join("");
  const cards = achados.map(i => { const r=respostas[i.id]||{}; return `<article class="card ${i.criticidade==='critico'?'crit':''}"><h3>${esc(i.texto)}</h3><div class="muted">${esc(i.id)} · ${esc(i.criticidade||"informativo")} · ${esc(r.status)}</div><p><b>Situação:</b> ${esc(r.situacao)}</p><p><b>Impacto:</b> ${esc(r.impacto)}</p><p><b>Indicação:</b> ${esc(r.indicacao)}</p><p><b>Observação:</b> ${esc(r.observacao)}</p></article>`; }).join("");
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(ref)}</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font:11pt Arial,sans-serif;color:#17212b;margin:0;line-height:1.42}.wrap{max-width:180mm;margin:auto}.cab{background:#17212b;color:#fff;padding:18px 22px;border-radius:0 0 8px 8px}.cab h1{margin:0;font-size:21px}.cab p{margin:5px 0;color:#d7e2e8}.brand{font-weight:900;letter-spacing:2px;color:#8fc9a8;margin-bottom:12px}.section{margin:18px 0;break-inside:avoid}.tag{display:inline-block;padding:5px 9px;border-radius:4px;background:#e6f0eb;color:#236145;font-weight:bold}.card{border:1px solid #d8dfe3;border-left:5px solid #b7791f;padding:10px 12px;margin:8px 0;break-inside:avoid}.card.crit{border-left-color:#b02a1e}.muted{color:#5b6b70;font-size:9pt}table{width:100%;border-collapse:collapse;font-size:9pt}th,td{border:1px solid #d8dfe3;padding:6px;text-align:left}th{background:#eef2f3}.foot{margin-top:24px;border-top:1px solid #d8dfe3;padding-top:8px;color:#5b6b70;font-size:8pt}@media print{.no-print{display:none}.cab{margin:-14mm -14mm 10mm;border-radius:0}}</style></head><body><main class="wrap"><header class="cab"><div class="brand">MOKED</div><h1>Diagnóstico Situacional</h1><p>${esc(projeto)} · ${esc(ref)}</p><p>${esc(criadoEm||new Date().toLocaleDateString("pt-BR"))} · Autor: ${esc(autor)} · Catálogo ${esc(catalogo?.versao)}</p><span class="tag">${pct}% de conformidade</span></header><section class="section"><h2>Resumo por categoria</h2><table><thead><tr><th>Categoria</th><th>Conformidade</th></tr></thead><tbody>${categorias}</tbody></table></section><section class="section"><h2>Indicadores gerais</h2><p>${conformes} itens conformes de ${total} considerados. Itens NA não entram no denominador; SD permanece contabilizado.</p></section><section class="section"><h2>Achados</h2>${cards||'<p>Nenhum item P, NC ou AN registrado.</p>'}</section><section class="section"><h2>Itens NA e SD</h2><p>${itens.filter(i=>["na","sd"].includes(respostas[i.id]?.status)).map(i=>`${esc(i.id)} — ${esc(i.texto)} (${esc(respostas[i.id]?.status)})`).join("<br>")||"Nenhum."}</p></section><footer class="foot">MOKED Consulting Security · Diagnóstico Situacional · ${esc(ref)}</footer></main><button class="no-print" onclick="window.print()">Salvar como PDF / Imprimir</button></body></html>`;
}

export function abrirPDFDiagnostico(dados) { const w=window.open("","_blank"); if(w){w.document.write(gerarHTMLDiagnostico(dados));w.document.close();} return w; }
