// ─────────────────────────────────────────────────────────────
// scripts/seed/catalogoSeed.mjs — DADOS PUROS do catálogo inicial
// Perfil: Centro Logístico · catalogoId centro_logistico_v1_0_0 · versão 1.0.0
//
// FONTE ÚNICA aprovada (Matriz v1.0.0): 8 categorias, 16 subcategorias,
// 110 itens. Transcrição fiel — nada inventado, removido, agrupado ou
// renomeado. Os seis IDs de 4 níveis são preservados literalmente.
//
// ⚠️ FORA de src/. NENHUM arquivo de src/ importa este módulo. O seed
// JAMAIS entra no bundle CRA nem é lido em runtime. Uso exclusivo do
// executor one-shot scripts/seed/run.mjs (Admin SDK, credencial fora do
// repositório). Após a carga, o Firestore é a fonte de verdade única e
// vencedora.
// ─────────────────────────────────────────────────────────────

export const CATALOGO_META = {
  catalogoId: "centro_logistico_v1_0_0",
  versao: "1.0.0",
  perfil: "centro_logistico",
  status: "publicado",
  // Regras declarativas de avaliação persistidas no doc raiz do catálogo.
  // Imutáveis por auditor; mudança exige NOVA versão de catálogo.
  statusPossiveisPadrao: ["conforme","parcial","nao_conforme","ausente_necessario","na","sem_dado"],
  statusQueExcluemDenominador: ["na"],
  statusQuePermanecemNoDenominador: ["sem_dado"],
  statusQueNaoContamComoAvaliados: ["na","sem_dado"],
};

// ordem persistida (1-based) para categorias e subcategorias.
export const CATEGORIAS = [
  { id: "D01", nome: "Portaria e Controle de Acesso", ordem: 1 },
  { id: "D02", nome: "CCO e Tecnologia", ordem: 2 },
  { id: "D03", nome: "Perímetro e Detecção", ordem: 3 },
  { id: "D04", nome: "Vias, Pátio e Áreas Comuns", ordem: 4 },
  { id: "D05", nome: "Equipamentos Operacionais", ordem: 5 },
  { id: "D06", nome: "Emergência, Saúde e Segurança", ordem: 6 },
  { id: "D07", nome: "Equipe, Escala e Procedimentos", ordem: 7 },
  { id: "D08", nome: "Governança, Risco e Manutenção", ordem: 8 },
];

export const SUBCATEGORIAS = [
  { id: "D01.01", categoria: "D01", nome: "Estrutura da portaria", ordem: 1 },
  { id: "D01.02", categoria: "D01", nome: "Operação de acesso", ordem: 2 },
  { id: "D01.03", categoria: "D01", nome: "Barreiras de acesso", ordem: 3 },
  { id: "D02.01", categoria: "D02", nome: "Centro de Controle Operacional", ordem: 4 },
  { id: "D02.02", categoria: "D02", nome: "CFTV e vídeo", ordem: 5 },
  { id: "D02.03", categoria: "D02", nome: "Conectividade e energia de TI", ordem: 6 },
  { id: "D03.01", categoria: "D03", nome: "Barreiras físicas", ordem: 7 },
  { id: "D03.02", categoria: "D03", nome: "Detecção e resposta", ordem: 8 },
  { id: "D04.01", categoria: "D04", nome: "Vias de acesso e pátio", ordem: 9 },
  { id: "D04.02", categoria: "D04", nome: "Áreas comuns", ordem: 10 },
  { id: "D05.01", categoria: "D05", nome: "Comunicação e resposta", ordem: 11 },
  { id: "D05.02", categoria: "D05", nome: "Materiais e ativos", ordem: 12 },
  { id: "D06.00", categoria: "D06", nome: "Emergência, Saúde e Segurança", ordem: 13 },
  { id: "D07.01", categoria: "D07", nome: "Quadro operacional", ordem: 14 },
  { id: "D07.02", categoria: "D07", nome: "Maturidade operacional", ordem: 15 },
  { id: "D08.00", categoria: "D08", nome: "Governança, Risco e Manutenção", ordem: 16 },
];

// 110 itens — ordem idêntica à Matriz (campo ordem 1-based). Regras globais em todos.
export const ITENS = [
  { id: "D01.01.01", categoria: "D01", subcategoria: "D01.01", texto: "Guarita e portas", criticidade: "relevante", aplicavelPadrao: true, ordem: 1, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.01.02", categoria: "D01", subcategoria: "D01.01", texto: "Fechaduras e eclusas", criticidade: "relevante", aplicavelPadrao: true, ordem: 2, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.01.03", categoria: "D01", subcategoria: "D01.01", texto: "Vidros, blindagem e visibilidade externa", criticidade: "relevante", aplicavelPadrao: true, ordem: 3, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.01.04", categoria: "D01", subcategoria: "D01.01", texto: "Mobiliário e ergonomia", criticidade: "informativo", aplicavelPadrao: true, ordem: 4, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.01.05", categoria: "D01", subcategoria: "D01.01", texto: "Iluminação, climatização e limpeza", criticidade: "informativo", aplicavelPadrao: true, ordem: 5, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.01.06", categoria: "D01", subcategoria: "D01.01", texto: "Banheiro, área de apoio e acessibilidade", criticidade: "informativo", aplicavelPadrao: true, ordem: 6, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.01", categoria: "D01", subcategoria: "D01.02", texto: "Visitantes e prestadores", criticidade: "relevante", aplicavelPadrao: true, ordem: 7, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.02", categoria: "D01", subcategoria: "D01.02", texto: "Credenciais e leitoras", criticidade: "relevante", aplicavelPadrao: true, ordem: 8, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.03", categoria: "D01", subcategoria: "D01.02", texto: "Chaves, lacres e guarda de ativos", criticidade: "relevante", aplicavelPadrao: true, ordem: 9, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.04", categoria: "D01", subcategoria: "D01.02", texto: "Interfone, telefone e comunicação", criticidade: "relevante", aplicavelPadrao: true, ordem: 10, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.05.01", categoria: "D01", subcategoria: "D01.02", texto: "Procedimento de entrada", criticidade: "relevante", aplicavelPadrao: true, ordem: 11, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.05.02", categoria: "D01", subcategoria: "D01.02", texto: "Procedimento de saída", criticidade: "relevante", aplicavelPadrao: true, ordem: 12, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.05.03", categoria: "D01", subcategoria: "D01.02", texto: "Procedimento de contingência", criticidade: "critico", aplicavelPadrao: true, ordem: 13, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.02.06", categoria: "D01", subcategoria: "D01.02", texto: "Segregação de pedestres e veículos", criticidade: "relevante", aplicavelPadrao: true, ordem: 14, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.01", categoria: "D01", subcategoria: "D01.03", texto: "Cancelas convencionais", criticidade: "relevante", aplicavelPadrao: true, ordem: 15, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.02", categoria: "D01", subcategoria: "D01.03", texto: "Cancelas de alta segurança", criticidade: "critico", aplicavelPadrao: false, ordem: 16, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.03", categoria: "D01", subcategoria: "D01.03", texto: "Bollards", criticidade: "relevante", aplicavelPadrao: false, ordem: 17, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.04", categoria: "D01", subcategoria: "D01.03", texto: "Dilaceradores", criticidade: "relevante", aplicavelPadrao: false, ordem: 18, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.05", categoria: "D01", subcategoria: "D01.03", texto: "Botoeiras e abertura local/remota", criticidade: "relevante", aplicavelPadrao: true, ordem: 19, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.06.01", categoria: "D01", subcategoria: "D01.03", texto: "Semáforos e sinalização operacional", criticidade: "informativo", aplicavelPadrao: true, ordem: 20, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.06.02", categoria: "D01", subcategoria: "D01.03", texto: "Totens de autoatendimento/orientação", criticidade: "informativo", aplicavelPadrao: false, ordem: 21, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D01.03.07", categoria: "D01", subcategoria: "D01.03", texto: "Eclusas de veículos e pessoas", criticidade: "critico", aplicavelPadrao: true, ordem: 22, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.01", categoria: "D02", subcategoria: "D02.01", texto: "Ambiente segregado e controle de entrada", criticidade: "critico", aplicavelPadrao: true, ordem: 23, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.02", categoria: "D02", subcategoria: "D02.01", texto: "Mesa, cadeiras e ergonomia", criticidade: "informativo", aplicavelPadrao: true, ordem: 24, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.03", categoria: "D02", subcategoria: "D02.01", texto: "Monitores: quantidade, posição e funcionalidade", criticidade: "relevante", aplicavelPadrao: true, ordem: 25, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.04", categoria: "D02", subcategoria: "D02.01", texto: "Computadores, teclado, joystick e periféricos", criticidade: "relevante", aplicavelPadrao: true, ordem: 26, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.05", categoria: "D02", subcategoria: "D02.01", texto: "Rack, cabeamento, fiação, tomadas e réguas", criticidade: "relevante", aplicavelPadrao: true, ordem: 27, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.06", categoria: "D02", subcategoria: "D02.01", texto: "Ar-condicionado, iluminação e nobreak", criticidade: "relevante", aplicavelPadrao: true, ordem: 28, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.01.07", categoria: "D02", subcategoria: "D02.01", texto: "POP de monitoramento e contingência", criticidade: "critico", aplicavelPadrao: true, ordem: 29, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.01", categoria: "D02", subcategoria: "D02.02", texto: "Cobertura de câmeras por área", criticidade: "critico", aplicavelPadrao: true, ordem: 30, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.02", categoria: "D02", subcategoria: "D02.02", texto: "Pontos cegos", criticidade: "critico", aplicavelPadrao: true, ordem: 31, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.03", categoria: "D02", subcategoria: "D02.02", texto: "Câmeras fixas, dome, speed dome e LPR", criticidade: "relevante", aplicavelPadrao: true, ordem: 32, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.04", categoria: "D02", subcategoria: "D02.02", texto: "NVR, servidores e armazenamento", criticidade: "critico", aplicavelPadrao: true, ordem: 33, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.05", categoria: "D02", subcategoria: "D02.02", texto: "Retenção e qualidade das imagens", criticidade: "critico", aplicavelPadrao: true, ordem: 34, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.06", categoria: "D02", subcategoria: "D02.02", texto: "VMS, software CFTV e licenças", criticidade: "relevante", aplicavelPadrao: true, ordem: 35, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.02.07", categoria: "D02", subcategoria: "D02.02", texto: "Acesso remoto e rastreabilidade", criticidade: "relevante", aplicavelPadrao: true, ordem: 36, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.01", categoria: "D02", subcategoria: "D02.03", texto: "Rede cabeada", criticidade: "relevante", aplicavelPadrao: true, ordem: 37, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.02", categoria: "D02", subcategoria: "D02.03", texto: "Wi-Fi operacional", criticidade: "informativo", aplicavelPadrao: true, ordem: 38, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.03", categoria: "D02", subcategoria: "D02.03", texto: "Internet principal", criticidade: "critico", aplicavelPadrao: true, ordem: 39, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.04", categoria: "D02", subcategoria: "D02.03", texto: "Estabilidade de internet", criticidade: "relevante", aplicavelPadrao: true, ordem: 40, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.05", categoria: "D02", subcategoria: "D02.03", texto: "Redundância de internet", criticidade: "relevante", aplicavelPadrao: true, ordem: 41, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.06", categoria: "D02", subcategoria: "D02.03", texto: "Firewall e ativos de rede", criticidade: "relevante", aplicavelPadrao: true, ordem: 42, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D02.03.07", categoria: "D02", subcategoria: "D02.03", texto: "Nobreak, gerador e autonomia elétrica", criticidade: "critico", aplicavelPadrao: true, ordem: 43, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.01.01", categoria: "D03", subcategoria: "D03.01", texto: "Muro, gradil e portões", criticidade: "critico", aplicavelPadrao: true, ordem: 44, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.01.02", categoria: "D03", subcategoria: "D03.01", texto: "Cerca elétrica", criticidade: "relevante", aplicavelPadrao: true, ordem: 45, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.01.03", categoria: "D03", subcategoria: "D03.01", texto: "Concertina e coroa-de-cristo", criticidade: "relevante", aplicavelPadrao: true, ordem: 46, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.01.04", categoria: "D03", subcategoria: "D03.01", texto: "Guard-rail e New Jersey", criticidade: "relevante", aplicavelPadrao: true, ordem: 47, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.01.05", categoria: "D03", subcategoria: "D03.01", texto: "Integridade de bases, pilares e fixações", criticidade: "relevante", aplicavelPadrao: true, ordem: 48, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.01", categoria: "D03", subcategoria: "D03.02", texto: "Fibra sensitiva e sensores", criticidade: "relevante", aplicavelPadrao: true, ordem: 49, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.02", categoria: "D03", subcategoria: "D03.02", texto: "Iluminação perimetral", criticidade: "critico", aplicavelPadrao: true, ordem: 50, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.03", categoria: "D03", subcategoria: "D03.02", texto: "CFTV perimetral", criticidade: "critico", aplicavelPadrao: true, ordem: 51, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.04", categoria: "D03", subcategoria: "D03.02", texto: "Pontos cegos e rotas de evasão", criticidade: "critico", aplicavelPadrao: true, ordem: 52, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.05", categoria: "D03", subcategoria: "D03.02", texto: "Vegetação, taludes, erosão e drenagem", criticidade: "relevante", aplicavelPadrao: true, ordem: 53, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D03.02.06", categoria: "D03", subcategoria: "D03.02", texto: "Integração com CCO e resposta a alarme", criticidade: "critico", aplicavelPadrao: true, ordem: 54, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.01", categoria: "D04", subcategoria: "D04.01", texto: "Pavimento, lombadas e drenagem", criticidade: "relevante", aplicavelPadrao: true, ordem: 55, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.02", categoria: "D04", subcategoria: "D04.01", texto: "Sinalização horizontal e vertical", criticidade: "relevante", aplicavelPadrao: true, ordem: 56, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.03", categoria: "D04", subcategoria: "D04.01", texto: "Faixas, velocidade e filas", criticidade: "relevante", aplicavelPadrao: true, ordem: 57, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.04", categoria: "D04", subcategoria: "D04.01", texto: "Docas, bolsão de caminhões e estacionamento", criticidade: "relevante", aplicavelPadrao: true, ordem: 58, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.05", categoria: "D04", subcategoria: "D04.01", texto: "Estacionamento de motos", criticidade: "informativo", aplicavelPadrao: true, ordem: 59, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.06", categoria: "D04", subcategoria: "D04.01", texto: "Rotas de emergência", criticidade: "critico", aplicavelPadrao: true, ordem: 60, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.01.07", categoria: "D04", subcategoria: "D04.01", texto: "Iluminação e segregação pedestre-veículo", criticidade: "relevante", aplicavelPadrao: true, ordem: 61, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.01", categoria: "D04", subcategoria: "D04.02", texto: "Calçadas, pisos e acessibilidade", criticidade: "relevante", aplicavelPadrao: true, ordem: 62, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.02", categoria: "D04", subcategoria: "D04.02", texto: "Telhados, coberturas e infiltrações", criticidade: "relevante", aplicavelPadrao: true, ordem: 63, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.03", categoria: "D04", subcategoria: "D04.02", texto: "Lixeiras, limpeza e conservação", criticidade: "informativo", aplicavelPadrao: true, ordem: 64, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.04", categoria: "D04", subcategoria: "D04.02", texto: "Banheiros, torneiras, mangueiras e áreas de apoio", criticidade: "informativo", aplicavelPadrao: true, ordem: 65, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.05", categoria: "D04", subcategoria: "D04.02", texto: "Refeitório, fumódromo e área de convivência", criticidade: "informativo", aplicavelPadrao: true, ordem: 66, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.06", categoria: "D04", subcategoria: "D04.02", texto: "Paisagismo e materiais abandonados", criticidade: "informativo", aplicavelPadrao: true, ordem: 67, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D04.02.07", categoria: "D04", subcategoria: "D04.02", texto: "Riscos de queda, impacto ou atropelamento", criticidade: "relevante", aplicavelPadrao: true, ordem: 68, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.01.01", categoria: "D05", subcategoria: "D05.01", texto: "Rádios HT", criticidade: "relevante", aplicavelPadrao: true, ordem: 69, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.01.02", categoria: "D05", subcategoria: "D05.01", texto: "Smartphones e comunicação de contingência", criticidade: "relevante", aplicavelPadrao: true, ordem: 70, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.01.03", categoria: "D05", subcategoria: "D05.01", texto: "Lanternas, cones e sinalização móvel", criticidade: "informativo", aplicavelPadrao: true, ordem: 71, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.01.04", categoria: "D05", subcategoria: "D05.01", texto: "Viatura ou carro tático", criticidade: "relevante", aplicavelPadrao: false, ordem: 72, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.01.05", categoria: "D05", subcategoria: "D05.01", texto: "Botão de pânico/coação (fixo ou móvel)", criticidade: "critico", aplicavelPadrao: false, ordem: 73, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.02.01", categoria: "D05", subcategoria: "D05.02", texto: "Equipamentos cadastrados no projeto", criticidade: "relevante", aplicavelPadrao: true, ordem: 74, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.02.02", categoria: "D05", subcategoria: "D05.02", texto: "Estado, identificação e rastreabilidade", criticidade: "relevante", aplicavelPadrao: true, ordem: 75, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.02.03", categoria: "D05", subcategoria: "D05.02", texto: "Manutenção preventiva e corretiva", criticidade: "relevante", aplicavelPadrao: true, ordem: 76, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.02.04", categoria: "D05", subcategoria: "D05.02", texto: "Materiais de operação e reposição", criticidade: "informativo", aplicavelPadrao: true, ordem: 77, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D05.02.05", categoria: "D05", subcategoria: "D05.02", texto: "Armazenamento e conservação", criticidade: "informativo", aplicavelPadrao: true, ordem: 78, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.01", categoria: "D06", subcategoria: "D06.00", texto: "Extintores e hidrantes", criticidade: "critico", aplicavelPadrao: true, ordem: 79, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.02", categoria: "D06", subcategoria: "D06.00", texto: "Sinalização e rotas de fuga", criticidade: "critico", aplicavelPadrao: true, ordem: 80, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.03", categoria: "D06", subcategoria: "D06.00", texto: "Iluminação de emergência", criticidade: "critico", aplicavelPadrao: true, ordem: 81, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.04", categoria: "D06", subcategoria: "D06.00", texto: "Portas corta-fogo", criticidade: "critico", aplicavelPadrao: true, ordem: 82, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.05", categoria: "D06", subcategoria: "D06.00", texto: "Brigada e ponto de encontro", criticidade: "relevante", aplicavelPadrao: true, ordem: 83, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.06", categoria: "D06", subcategoria: "D06.00", texto: "Plano de emergência", criticidade: "critico", aplicavelPadrao: true, ordem: 84, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.07", categoria: "D06", subcategoria: "D06.00", texto: "Simulados, validade e inspeções", criticidade: "relevante", aplicavelPadrao: true, ordem: 85, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D06.00.08", categoria: "D06", subcategoria: "D06.00", texto: "Queda de energia, incêndio, invasão e acidente", criticidade: "critico", aplicavelPadrao: true, ordem: 86, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.01", categoria: "D07", subcategoria: "D07.01", texto: "Quadro recomendado", criticidade: "relevante", aplicavelPadrao: true, ordem: 87, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.02", categoria: "D07", subcategoria: "D07.01", texto: "Quadro aceitável", criticidade: "relevante", aplicavelPadrao: true, ordem: 88, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.03", categoria: "D07", subcategoria: "D07.01", texto: "Quadro atual", criticidade: "relevante", aplicavelPadrao: true, ordem: 89, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.04", categoria: "D07", subcategoria: "D07.01", texto: "Postos, turnos e rendições", criticidade: "relevante", aplicavelPadrao: true, ordem: 90, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.05", categoria: "D07", subcategoria: "D07.01", texto: "Cobertura de férias e afastamentos", criticidade: "relevante", aplicavelPadrao: true, ordem: 91, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.06", categoria: "D07", subcategoria: "D07.01", texto: "Horários de pico e postos descobertos", criticidade: "critico", aplicavelPadrao: true, ordem: 92, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.01.07", categoria: "D07", subcategoria: "D07.01", texto: "Classificação: adequado, atenção, insuficiente ou crítico", criticidade: "relevante", aplicavelPadrao: true, ordem: 93, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.01", categoria: "D07", subcategoria: "D07.02", texto: "Líder, ronda, CCO, portaria e tático", criticidade: "relevante", aplicavelPadrao: true, ordem: 94, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.02", categoria: "D07", subcategoria: "D07.02", texto: "Treinamento, reciclagem e integração", criticidade: "relevante", aplicavelPadrao: true, ordem: 95, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.03", categoria: "D07", subcategoria: "D07.02", texto: "Uniforme e materiais individuais", criticidade: "informativo", aplicavelPadrao: true, ordem: 96, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.04", categoria: "D07", subcategoria: "D07.02", texto: "Livro de ocorrências e comunicação", criticidade: "relevante", aplicavelPadrao: true, ordem: 97, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.05", categoria: "D07", subcategoria: "D07.02", texto: "Supervisão e auditoria de turno", criticidade: "relevante", aplicavelPadrao: true, ordem: 98, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.06", categoria: "D07", subcategoria: "D07.02", texto: "MNP", criticidade: "critico", aplicavelPadrao: true, ordem: 99, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.07", categoria: "D07", subcategoria: "D07.02", texto: "POP", criticidade: "critico", aplicavelPadrao: true, ordem: 100, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.08", categoria: "D07", subcategoria: "D07.02", texto: "Plano de contingência", criticidade: "critico", aplicavelPadrao: true, ordem: 101, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D07.02.09", categoria: "D07", subcategoria: "D07.02", texto: "Organograma e responsabilidades", criticidade: "relevante", aplicavelPadrao: true, ordem: 102, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.01", categoria: "D08", subcategoria: "D08.00", texto: "Mapa de risco e geolocalização", criticidade: "relevante", aplicavelPadrao: true, ordem: 103, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.02", categoria: "D08", subcategoria: "D08.00", texto: "Vulnerabilidades abertas e histórico", criticidade: "relevante", aplicavelPadrao: true, ordem: 104, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.03", categoria: "D08", subcategoria: "D08.00", texto: "Plano de manutenção", criticidade: "relevante", aplicavelPadrao: true, ordem: 105, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.04", categoria: "D08", subcategoria: "D08.00", texto: "Responsáveis por cada ação", criticidade: "relevante", aplicavelPadrao: true, ordem: 106, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.05", categoria: "D08", subcategoria: "D08.00", texto: "Integração com administração, facilities e obra", criticidade: "informativo", aplicavelPadrao: true, ordem: 107, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.06", categoria: "D08", subcategoria: "D08.00", texto: "Expansões, fases de obra e mudanças de fluxo", criticidade: "relevante", aplicavelPadrao: true, ordem: 108, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.07", categoria: "D08", subcategoria: "D08.00", texto: "Indicadores, prazos e revisão do diagnóstico", criticidade: "relevante", aplicavelPadrao: true, ordem: 109, origem: "manual", fonte_auto: null, deprecado: false },
  { id: "D08.00.08", categoria: "D08", subcategoria: "D08.00", texto: "Registros positivos e melhorias já aplicadas", criticidade: "informativo", aplicavelPadrao: true, ordem: 110, origem: "manual", fonte_auto: null, deprecado: false },
];

export const CATALOGO_SEED = {
  ...CATALOGO_META,
  categorias: CATEGORIAS,
  subcategorias: SUBCATEGORIAS,
  itens: ITENS,
};

export default CATALOGO_SEED;